name: "ðŸ³ Mirror"

on:
  workflow_dispatch:
  push:
    branches:
      - '*'

jobs:
  mirror_matrix_generator:
    name: "ðŸ³ Mirror Matrix Generator"
    runs-on: ubuntu-latest
    outputs:
      dockerinfo: ${{ steps.set-matrix.outputs.dockerinfo }}
    steps:
      - name: "ðŸ“¥  Fetching Repository Contents"
        uses: actions/checkout@main

      - id: set-matrix
        run: php .github/scripts/matrix.php

  mirror_image:
    runs-on: ubuntu-latest
    needs: mirror_matrix_generator
    name: "ðŸš€  ${{ matrix.dockerinfo.name }} - Publisher"
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        dockerinfo: ${{fromJson(needs.mirror_matrix_generator.outputs.dockerinfo)}}
    steps:
      - name: "ðŸ“¥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "ðŸ’¾  Github Repository Metadata"
        uses: varunsridharan/action-repository-meta@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "âš¡ Setup DockerFile"
        run: |
          echo " " >> ./${{matrix.dockerinfo.file}}
          echo "LABEL org.opencontainers.image.source=\"https://github.com/${GITHUB_REPOSITORY}/\"" >> ./${{matrix.dockerinfo.file}}
          echo "LABEL org.opencontainers.image.url=\"https://github.com/${GITHUB_REPOSITORY}/\"" >> ./${{matrix.dockerinfo.file}}
          echo "LABEL org.opencontainers.image.documentation=\"https://github.com/${GITHUB_REPOSITORY}/\"" >> ./${{matrix.dockerinfo.file}}
          echo "LABEL org.opencontainers.image.vendor=\"Unofficial Docker Hub Mirror\"" >> ./${{matrix.dockerinfo.file}}
          cat ./${{matrix.dockerinfo.file}}

      - name: "âš¡ Docker QEMU"
        uses: docker/setup-qemu-action@master

      - name: "âš¡ Docker BuildX"
        uses: docker/setup-buildx-action@master

      - name: "ðŸ”’  Log into GitHub Container Registry"
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_WRITE_PACKAGES }}

      - name: "ðŸŽ‰  Build &  ðŸš€  Publish"
        uses: docker/build-push-action@master
        with:
          file: ./${{ matrix.dockerinfo.file }}
          push: true
          tags: |
            ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ matrix.dockerinfo.name }}
